// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogmrcygjqqugcwzaioxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbXJjeWdqcXF1Z2N3emFpb3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDE4ODIsImV4cCI6MjA3MjQxNzg4Mn0.zFWWKvJ3k0xcZpJqSCdFYT4HqJZ0TplxnrnHEIoi1b4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});